POST http://localhost:3001/tasks
Content-Type: application/json

{
  "title": "Title of the task 3",
  "dueDate": "2025-01-01T12:00:00Z",
  "description": "learn fullstack",
  "priority": "normal",
  "status": "todo"
}